### ISSUE TITLE
Building error in brnelib: "initializer expression refers to iteration variable 'i'"

### ISSUE THREAD

**Issue by zyu494** [MurpheyLab/brne#1]
Hi,

I'm encountering an error in the compute_costs function in the brne.cpp file located at /brne/brne_nav/brnelib/src/brne.cpp. The error is shown as follows:
![error](https://github.com/user-attachments/assets/4f927594-7b40-41fa-88bc-c30d7abc909b)
I am using the following versions as listed in the dependency section: Armadillo: 12.6.6, Catch2: Version 3. I would appreciate any guidance or solution to resolve this issue. If there are any known fixes or workarounds, I'd love to hear about them.

Thanks in advance for your help!

**Comment by MaxMSun** [comment]
Hi!

This error is usually related to OpenMP, which version do you have?

Muchen

**Comment by zyu494** [comment]
Hi,
Thanks for your prompt response! Currently, I'm using gcc 9.4.0 and the version of OpenMP seems to be 5.0.

**Comment by MaxMSun** [comment]
The error is likely caused by how "j" is initialized in Line 132 (the initialization of "j", which is parallelized with OpenMP, should not depend on the initialization of "i", which is also parallelized with OpenMP). Could you please try the following change and let me know how it goes (starting with line 131)?

```C++
for (auto i=0; i<size; i++){
    for (auto j=0; j<size; j++){
        if (j < i) {continue;}
        ...
    }
}
```

If it doesn't work, you can also try to replace line 130 with "#pragma omp parallel for", in which case only the outer loop will be parallelized.

Thank you!

**Comment by zyu494** [comment]
Thanks for your suggestions. After replacing line 130 with "#pragma omp parallel for", we solved this problem. We really appreciate your help!

**Comment by MaxMSun** [comment]
No problem! Marked the issue as closed.
